add Geoapify Provider
smeijer/leaflet-geosearch pull request #361
Opened 2023-03-31 12:49 UTC by CarolineVantim

Added provider for communication with the Geoapify API.

2023-04-05 12:39 UTC, smeijer requested changes
Hi! This looks great. Can you revert the changes to package.json so we can merge?

2023-04-05 13:35 UTC, CarolineVantim commented
Changes made

2023-04-18 13:51 UTC, CarolineVantim commented
Stephan, could you check if my adjustments are correct?

2023-04-18 16:44 UTC, smeijer commented on src/providers/__tests__/geoapifyProvider.spec.js
> +      '1214-1224 West Van Buren Street, Chicago, IL 60607, United States of America'
```suggestion
      '1214-1224 West Van Buren Street, Chicago, IL 60607, United States of America',
```

2023-04-18 18:27 UTC, smeijer approved these changes
Sorry, completely slipped my mind. Things are looking good now. Thanks so much!

2023-04-18 18:27 UTC, merged

2023-04-18 18:59 UTC, smeijer commented
:tada: This PR is included in version 3.8.0 :tada:

The release is available on:
- [npm package (@develop dist-tag)](https://www.npmjs.com/package/leaflet-geosearch/v/3.8.0)
- [GitHub release](https://github.com/smeijer/leaflet-geosearch/releases/tag/v3.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2026-10-27 14:28 UTC, ramazansancar commented
@all-contributors please add @CarolineVantim for code, doc, test